Repository Codifica2/task-now-backend, pull requests merged in 2023-05, with the labels that each got.

#13 Fix/task model task 21
  models/Category.js
  models/Task.js
Labels: refactor

#24 test: install test framework
  controllers/tasks.js
  package-lock.json
  package.json
  test/models.js
  test/tasksEndpoint.js
Labels: enhancement

#25 Feat/protect endpoints task 27
  controllers/tasks.js
  controllers/users.js
  middleware/errorHandler.js
  middleware/verifyToken.js
Labels: enhancement

#26 Feat/category endpoints task 28
  app.js
  controllers/categories.js
  controllers/users.js
Labels: enhancement

#27 fix: remove usersRouter copy
  controllers/users.js
Labels: refactor

#30 Test/pedro tests
  package-lock.json
  package.json
  test/tasksEndpoint.js
Labels: test
